include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    always_use_package_imports: true
    prefer_single_quotes: true

analyzer:
  plugins:
    - custom_lint
  errors:
    asset_does_not_exist: ignore

custom_lint:
  rules:
    - avoid_manual_providers_as_generated_provider_dependency: false
