/**
 * 必要なパッケージのインストールとして下記を実行
 * flutter pub run build_runner build --delete-conflicting-outputs
 * 参考：https://pub.dev/packages/freezed
 * flutter pub add freezed_annotation
 * flutter pub add --dev build_runner
 * flutter pub add --dev freezed
 * flutter pub add json_annotation
 * flutter pub add --dev json_serializable
 * 参考：https://github.com/rrousselGit/freezed
 */
// This file is "main.dart"
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'answer_browse_data.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.

@freezed
class AnswerBrowseData with _$AnswerBrowseData {
  const factory AnswerBrowseData({
    required String AnswerText, //解答
    required String email, //email
    required DateTime answerCreatedDate, //解答の作成日
  }) = _AnswerBrowseData;
}
