name: Check and test the source code with flutter lint
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Check the source code with flutter lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.1.0
        with:
          flutter-version: "3.13.4"
      - name: Create dot env file
        run: touch .env
      - name: Install packages
        run: flutter pub get
      - name: Linter
        run: flutter analyze
      - name: Test
        run: flutter test
